sudo: required
language: java
jdk:
- oraclejdk8

services:
- docker

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: bash docker_push.sh
  skip_cleanup: true
  on:
    branch: master
